//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>About</summary>
	[PublishedModel("about")]
	public partial class About : PublishedContentModel, IFeaturedBanner, IOfficesAboveTheFold, ISEO, IXmlSiteMapSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "about";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<About, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public About(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Article Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("articleDescription")]
		public IHtmlString ArticleDescription => this.Value<IHtmlString>("articleDescription");

		///<summary>
		/// Article Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("articleHeading")]
		public IHtmlString ArticleHeading => this.Value<IHtmlString>("articleHeading");

		///<summary>
		/// Awards Images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("awardsImages")]
		public IEnumerable<IPublishedContent> AwardsImages => this.Value<IEnumerable<IPublishedContent>>("awardsImages");

		///<summary>
		/// Awards Section Bg: Transparent Patterned Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("awardsSectionBg")]
		public IPublishedContent AwardsSectionBg => this.Value<IPublishedContent>("awardsSectionBg");

		///<summary>
		/// Awards Section Heading: H2 and White Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("awardsSectionHeading")]
		public IHtmlString AwardsSectionHeading => this.Value<IHtmlString>("awardsSectionHeading");

		///<summary>
		/// KMC Advantage Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageDescription")]
		public IHtmlString KMcadvantageDescription => this.Value<IHtmlString>("kMCAdvantageDescription");

		///<summary>
		/// KMC Advantage Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageHeading")]
		public IHtmlString KMcadvantageHeading => this.Value<IHtmlString>("kMCAdvantageHeading");

		///<summary>
		/// KMC Advantage Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageImageAltTag")]
		public string KMcadvantageImageAltTag => this.Value<string>("kMCAdvantageImageAltTag");

		///<summary>
		/// KMC Advantage Supporting Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageSupportingImage")]
		public IPublishedContent KMcadvantageSupportingImage => this.Value<IPublishedContent>("kMCAdvantageSupportingImage");

		///<summary>
		/// Managed Floors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("managedFloors")]
		public IHtmlString ManagedFloors => this.Value<IHtmlString>("managedFloors");

		///<summary>
		/// Mission
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("mission")]
		public IHtmlString Mission => this.Value<IHtmlString>("mission");

		///<summary>
		/// Mission Vision Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("missionVisionImageAltTag")]
		public IHtmlString MissionVisionImageAltTag => this.Value<IHtmlString>("missionVisionImageAltTag");

		///<summary>
		/// Mission Vision Supporting Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("missionVisionSupportingImage")]
		public IPublishedContent MissionVisionSupportingImage => this.Value<IPublishedContent>("missionVisionSupportingImage");

		///<summary>
		/// Mission Vision Texture Bg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("missionVisionTextureBg")]
		public IPublishedContent MissionVisionTextureBg => this.Value<IPublishedContent>("missionVisionTextureBg");

		///<summary>
		/// Office Locations
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeLocations")]
		public IHtmlString OfficeLocations => this.Value<IHtmlString>("officeLocations");

		///<summary>
		/// People Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("peopleDescription")]
		public IHtmlString PeopleDescription => this.Value<IHtmlString>("peopleDescription");

		///<summary>
		/// People Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("peopleHeading")]
		public IHtmlString PeopleHeading => this.Value<IHtmlString>("peopleHeading");

		///<summary>
		/// Total Workspace
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("totalWorkspace")]
		public IHtmlString TotalWorkspace => this.Value<IHtmlString>("totalWorkspace");

		///<summary>
		/// Vision
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("vision")]
		public IHtmlString Vision => this.Value<IHtmlString>("vision");

		///<summary>
		/// Workspace Landscape Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspaceLandscapeHeading")]
		public IHtmlString WorkspaceLandscapeHeading => this.Value<IHtmlString>("workspaceLandscapeHeading");

		///<summary>
		/// Workspace Texture Bg
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspaceTextureBg")]
		public IPublishedContent WorkspaceTextureBg => this.Value<IPublishedContent>("workspaceTextureBg");

		///<summary>
		/// Workstations
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workstations")]
		public IHtmlString Workstations => this.Value<IHtmlString>("workstations");

		///<summary>
		/// Banner Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerAltTag")]
		public string BannerAltTag => FeaturedBanner.GetBannerAltTag(this);

		///<summary>
		/// Banner Image - Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerImageDesktop")]
		public IPublishedContent BannerImageDesktop => FeaturedBanner.GetBannerImageDesktop(this);

		///<summary>
		/// Banner Image - Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerImageMobile")]
		public IPublishedContent BannerImageMobile => FeaturedBanner.GetBannerImageMobile(this);

		///<summary>
		/// Banner Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerLink")]
		public string BannerLink => FeaturedBanner.GetBannerLink(this);

		///<summary>
		/// Banner on Page: If a banner should appear on a page, enable the button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("showBannerOnPage")]
		public bool ShowBannerOnPage => FeaturedBanner.GetShowBannerOnPage(this);

		///<summary>
		/// Above the Fold Button Link: Add redirect link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldButtonLink")]
		public string AboveTheFoldButtonLink => OfficesAboveTheFold.GetAboveTheFoldButtonLink(this);

		///<summary>
		/// Above the Fold Button Text: primary button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldButtonText")]
		public string AboveTheFoldButtonText => OfficesAboveTheFold.GetAboveTheFoldButtonText(this);

		///<summary>
		/// Above the Fold Col 1 Bg Image: Transparent Texture Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldCol1BgImage")]
		public IPublishedContent AboveTheFoldCol1BgImage => OfficesAboveTheFold.GetAboveTheFoldCol1BgImage(this);

		///<summary>
		/// Above the Fold Col 2 Bg Image: Single Image Background. Not applicable on carousel items as background.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldCol2BgImage")]
		public IPublishedContent AboveTheFoldCol2BgImage => OfficesAboveTheFold.GetAboveTheFoldCol2BgImage(this);

		///<summary>
		/// Above the Fold Description: paragraph
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldDescription")]
		public IHtmlString AboveTheFoldDescription => OfficesAboveTheFold.GetAboveTheFoldDescription(this);

		///<summary>
		/// Above the Fold Heading: h1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldHeading")]
		public IHtmlString AboveTheFoldHeading => OfficesAboveTheFold.GetAboveTheFoldHeading(this);

		///<summary>
		/// Above the Fold Sub Heading: h2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldSubHeading")]
		public IHtmlString AboveTheFoldSubHeading => OfficesAboveTheFold.GetAboveTheFoldSubHeading(this);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEO.GetMetaDescription(this);

		///<summary>
		/// Navigation Item Name: Input name of nav item if it's different from the page name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("navigationItemName")]
		public string NavigationItemName => SEO.GetNavigationItemName(this);

		///<summary>
		/// Og Image: 600 x 600 px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("ogImage")]
		public IPublishedContent OgImage => SEO.GetOgImage(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => SEO.GetPageTitle(this);

		///<summary>
		/// Schema Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("schema")]
		public IEnumerable<IPublishedElement> Schema => SEO.GetSchema(this);

		///<summary>
		/// Structured Data: Add Structured Data from Schema.org
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("structuredData")]
		public string StructuredData => SEO.GetStructuredData(this);

		///<summary>
		/// Hide From Xml SiteMap: Whether to show this page on the XML Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("hideFromXmlSiteMap")]
		public bool HideFromXmlSiteMap => XmlSiteMapSettings.GetHideFromXmlSiteMap(this);

		///<summary>
		/// Search Engine Change Frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public string SearchEngineChangeFrequency => XmlSiteMapSettings.GetSearchEngineChangeFrequency(this);

		///<summary>
		/// Search Engine Relative Priority: Indicate the relevant priority of this page compared relatively to the rest of the site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public decimal SearchEngineRelativePriority => XmlSiteMapSettings.GetSearchEngineRelativePriority(this);
	}
}
