//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Customized Office Floors</summary>
	[PublishedModel("customizedOfficeFloors")]
	public partial class CustomizedOfficeFloors : PublishedContentModel, IFAqsection, IOfficesAboveTheFold, IOfficesOverview, IOfficeTypeProperties, ISEO, IXmlSiteMapSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "customizedOfficeFloors";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<CustomizedOfficeFloors, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public CustomizedOfficeFloors(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Branded Office Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("brandedOfficeDescription")]
		public IHtmlString BrandedOfficeDescription => this.Value<IHtmlString>("brandedOfficeDescription");

		///<summary>
		/// Branded Office Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("brandedOfficeHeading")]
		public IHtmlString BrandedOfficeHeading => this.Value<IHtmlString>("brandedOfficeHeading");

		///<summary>
		/// Branded Office Sub Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("brandedOfficeSubHeading")]
		public string BrandedOfficeSubHeading => this.Value<string>("brandedOfficeSubHeading");

		///<summary>
		/// Branded Office Supporting Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("brandedOfficeSupportingImage")]
		public IPublishedContent BrandedOfficeSupportingImage => this.Value<IPublishedContent>("brandedOfficeSupportingImage");

		///<summary>
		/// Branded Office Supporting Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("brandedOfficeSupportingImageAltTag")]
		public string BrandedOfficeSupportingImageAltTag => this.Value<string>("brandedOfficeSupportingImageAltTag");

		///<summary>
		/// Case Study 1 Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy1Description")]
		public string CaseStudy1Description => this.Value<string>("caseStudy1Description");

		///<summary>
		/// Case Study 1 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy1Image")]
		public IPublishedContent CaseStudy1Image => this.Value<IPublishedContent>("caseStudy1Image");

		///<summary>
		/// Case Study 1 Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy1Link")]
		public string CaseStudy1Link => this.Value<string>("caseStudy1Link");

		///<summary>
		/// Case Study 1 Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy1Title")]
		public string CaseStudy1Title => this.Value<string>("caseStudy1Title");

		///<summary>
		/// Case Study 2 Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy2Description")]
		public string CaseStudy2Description => this.Value<string>("caseStudy2Description");

		///<summary>
		/// Case Study 2 Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy2Image")]
		public IPublishedContent CaseStudy2Image => this.Value<IPublishedContent>("caseStudy2Image");

		///<summary>
		/// Case Study 2 Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy2Link")]
		public string CaseStudy2Link => this.Value<string>("caseStudy2Link");

		///<summary>
		/// Case Study 2 Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("caseStudy2Title")]
		public string CaseStudy2Title => this.Value<string>("caseStudy2Title");

		///<summary>
		/// Customized Office Floor Details: Customize columns and text here.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeFloorDetails")]
		public IHtmlString CustomizedOfficeFloorDetails => this.Value<IHtmlString>("customizedOfficeFloorDetails");

		///<summary>
		/// Customized Office Floor Heading: H3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeFloorHeading")]
		public string CustomizedOfficeFloorHeading => this.Value<string>("customizedOfficeFloorHeading");

		///<summary>
		/// Customized Office Floor Icon: add .png icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeFloorIcon")]
		public IPublishedContent CustomizedOfficeFloorIcon => this.Value<IPublishedContent>("customizedOfficeFloorIcon");

		///<summary>
		/// Customized Office Floors Button Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeFloorsButtonLink")]
		public string CustomizedOfficeFloorsButtonLink => this.Value<string>("customizedOfficeFloorsButtonLink");

		///<summary>
		/// Customized Office Floors Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeFloorsButtonText")]
		public string CustomizedOfficeFloorsButtonText => this.Value<string>("customizedOfficeFloorsButtonText");

		///<summary>
		/// Customized Office Solutions Bg Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeSolutionsBgImage")]
		public IPublishedContent CustomizedOfficeSolutionsBgImage => this.Value<IPublishedContent>("customizedOfficeSolutionsBgImage");

		///<summary>
		/// Customized Office Solutions Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customizedOfficeSolutionsHeading")]
		public IHtmlString CustomizedOfficeSolutionsHeading => this.Value<IHtmlString>("customizedOfficeSolutionsHeading");

		///<summary>
		/// Enterprise Works Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("enterpriseWorksDescription")]
		public IHtmlString EnterpriseWorksDescription => this.Value<IHtmlString>("enterpriseWorksDescription");

		///<summary>
		/// Enterprise Works Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("enterpriseWorksHeading")]
		public IHtmlString EnterpriseWorksHeading => this.Value<IHtmlString>("enterpriseWorksHeading");

		///<summary>
		/// Enterprise Works Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("enterpriseWorksImageAltTag")]
		public string EnterpriseWorksImageAltTag => this.Value<string>("enterpriseWorksImageAltTag");

		///<summary>
		/// Enterprise Works Supporting Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("enterpriseWorksSupportingImage")]
		public IPublishedContent EnterpriseWorksSupportingImage => this.Value<IPublishedContent>("enterpriseWorksSupportingImage");

		///<summary>
		/// KMC Advantage Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageDescription")]
		public IHtmlString KMcadvantageDescription => this.Value<IHtmlString>("kMCAdvantageDescription");

		///<summary>
		/// KMC Advantage Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageHeading")]
		public IHtmlString KMcadvantageHeading => this.Value<IHtmlString>("kMCAdvantageHeading");

		///<summary>
		/// KMC Advantage Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageImageAltTag")]
		public string KMcadvantageImageAltTag => this.Value<string>("kMCAdvantageImageAltTag");

		///<summary>
		/// KMC Advantage Supporting Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCAdvantageSupportingImage")]
		public IPublishedContent KMcadvantageSupportingImage => this.Value<IPublishedContent>("kMCAdvantageSupportingImage");

		///<summary>
		/// Your Office Floor Button Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("yourOfficeFloorButtonLink")]
		public string YourOfficeFloorButtonLink => this.Value<string>("yourOfficeFloorButtonLink");

		///<summary>
		/// Your Office Floor Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("yourOfficeFloorButtonText")]
		public string YourOfficeFloorButtonText => this.Value<string>("yourOfficeFloorButtonText");

		///<summary>
		/// Your Office Floor Details
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("yourOfficeFloorDetails")]
		public IHtmlString YourOfficeFloorDetails => this.Value<IHtmlString>("yourOfficeFloorDetails");

		///<summary>
		/// Your Office Floor Heading: H3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("yourOfficeFloorHeading")]
		public string YourOfficeFloorHeading => this.Value<string>("yourOfficeFloorHeading");

		///<summary>
		/// Your Office Floor Icon: .png icon
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("yourOfficeFloorIcon")]
		public IPublishedContent YourOfficeFloorIcon => this.Value<IPublishedContent>("yourOfficeFloorIcon");

		///<summary>
		/// Answer 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("answer1")]
		public IHtmlString Answer1 => FAqsection.GetAnswer1(this);

		///<summary>
		/// Answer 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("answer2")]
		public IHtmlString Answer2 => FAqsection.GetAnswer2(this);

		///<summary>
		/// Answer 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("answer3")]
		public IHtmlString Answer3 => FAqsection.GetAnswer3(this);

		///<summary>
		/// Answer 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("answer4")]
		public IHtmlString Answer4 => FAqsection.GetAnswer4(this);

		///<summary>
		/// Answer 5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("answer5")]
		public IHtmlString Answer5 => FAqsection.GetAnswer5(this);

		///<summary>
		/// FAQ Heading: Heading for FAQ Section
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("fAQHeading")]
		public string FAqheading => FAqsection.GetFAqheading(this);

		///<summary>
		/// Question 1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("question1")]
		public string Question1 => FAqsection.GetQuestion1(this);

		///<summary>
		/// Question 2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("question2")]
		public string Question2 => FAqsection.GetQuestion2(this);

		///<summary>
		/// Question 3
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("question3")]
		public string Question3 => FAqsection.GetQuestion3(this);

		///<summary>
		/// Question 4
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("question4")]
		public string Question4 => FAqsection.GetQuestion4(this);

		///<summary>
		/// Question 5
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("question5")]
		public string Question5 => FAqsection.GetQuestion5(this);

		///<summary>
		/// Above the Fold Button Link: Add redirect link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldButtonLink")]
		public string AboveTheFoldButtonLink => OfficesAboveTheFold.GetAboveTheFoldButtonLink(this);

		///<summary>
		/// Above the Fold Button Text: primary button
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldButtonText")]
		public string AboveTheFoldButtonText => OfficesAboveTheFold.GetAboveTheFoldButtonText(this);

		///<summary>
		/// Above the Fold Col 1 Bg Image: Transparent Texture Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldCol1BgImage")]
		public IPublishedContent AboveTheFoldCol1BgImage => OfficesAboveTheFold.GetAboveTheFoldCol1BgImage(this);

		///<summary>
		/// Above the Fold Col 2 Bg Image: Single Image Background. Not applicable on carousel items as background.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldCol2BgImage")]
		public IPublishedContent AboveTheFoldCol2BgImage => OfficesAboveTheFold.GetAboveTheFoldCol2BgImage(this);

		///<summary>
		/// Above the Fold Description: paragraph
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldDescription")]
		public IHtmlString AboveTheFoldDescription => OfficesAboveTheFold.GetAboveTheFoldDescription(this);

		///<summary>
		/// Above the Fold Heading: h1
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldHeading")]
		public IHtmlString AboveTheFoldHeading => OfficesAboveTheFold.GetAboveTheFoldHeading(this);

		///<summary>
		/// Above the Fold Sub Heading: h2
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("aboveTheFoldSubHeading")]
		public IHtmlString AboveTheFoldSubHeading => OfficesAboveTheFold.GetAboveTheFoldSubHeading(this);

		///<summary>
		/// Bg Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bgImage")]
		public IPublishedContent BgImage => OfficesOverview.GetBgImage(this);

		///<summary>
		/// Bg Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bgImageAltTag")]
		public string BgImageAltTag => OfficesOverview.GetBgImageAltTag(this);

		///<summary>
		/// Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("buttonText")]
		public string ButtonText => OfficesOverview.GetButtonText(this);

		///<summary>
		/// Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("description")]
		public IHtmlString Description => OfficesOverview.GetDescription(this);

		///<summary>
		/// Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("heading")]
		public IHtmlString Heading => OfficesOverview.GetHeading(this);

		///<summary>
		/// Office Sub Type Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeSubTypeButtonText")]
		public string OfficeSubTypeButtonText => OfficeTypeProperties.GetOfficeSubTypeButtonText(this);

		///<summary>
		/// Office Sub Type Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeSubTypeDescription")]
		public IHtmlString OfficeSubTypeDescription => OfficeTypeProperties.GetOfficeSubTypeDescription(this);

		///<summary>
		/// Office Sub Type Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeSubTypeHeading")]
		public IHtmlString OfficeSubTypeHeading => OfficeTypeProperties.GetOfficeSubTypeHeading(this);

		///<summary>
		/// Office Sub Type Image Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeSubTypeImageAltTag")]
		public string OfficeSubTypeImageAltTag => OfficeTypeProperties.GetOfficeSubTypeImageAltTag(this);

		///<summary>
		/// Office Sub Type Sub Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeSubTypeSubHeading")]
		public IHtmlString OfficeSubTypeSubHeading => OfficeTypeProperties.GetOfficeSubTypeSubHeading(this);

		///<summary>
		/// Office Sub Type Supporting Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("officeSubTypeSupportingImage")]
		public IPublishedContent OfficeSubTypeSupportingImage => OfficeTypeProperties.GetOfficeSubTypeSupportingImage(this);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEO.GetMetaDescription(this);

		///<summary>
		/// Navigation Item Name: Input name of nav item if it's different from the page name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("navigationItemName")]
		public string NavigationItemName => SEO.GetNavigationItemName(this);

		///<summary>
		/// Og Image: 600 x 600 px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("ogImage")]
		public IPublishedContent OgImage => SEO.GetOgImage(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => SEO.GetPageTitle(this);

		///<summary>
		/// Schema Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("schema")]
		public IEnumerable<IPublishedElement> Schema => SEO.GetSchema(this);

		///<summary>
		/// Structured Data: Add Structured Data from Schema.org
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("structuredData")]
		public string StructuredData => SEO.GetStructuredData(this);

		///<summary>
		/// Hide From Xml SiteMap: Whether to show this page on the XML Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("hideFromXmlSiteMap")]
		public bool HideFromXmlSiteMap => XmlSiteMapSettings.GetHideFromXmlSiteMap(this);

		///<summary>
		/// Search Engine Change Frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public string SearchEngineChangeFrequency => XmlSiteMapSettings.GetSearchEngineChangeFrequency(this);

		///<summary>
		/// Search Engine Relative Priority: Indicate the relevant priority of this page compared relatively to the rest of the site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public decimal SearchEngineRelativePriority => XmlSiteMapSettings.GetSearchEngineRelativePriority(this);
	}
}
