//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>Event</summary>
	[PublishedModel("event")]
	public partial class Event : PublishedContentModel, ISEO, IXmlSiteMapSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "event";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Event, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public Event(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Custom Form Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customFormHeading")]
		public string CustomFormHeading => this.Value<string>("customFormHeading");

		///<summary>
		/// Custom Form Script: Paste the Hubspot form script in the text area if its a custom form.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customFormScript")]
		public string CustomFormScript => this.Value<string>("customFormScript");

		///<summary>
		/// Custom KMC Form?: Enable this if the event registration form is customized.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("customKMCForm")]
		public bool CustomKmcform => this.Value<bool>("customKMCForm");

		///<summary>
		/// Enable Manual Input?: Enable for Manual Input of Date and Time
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("enableManualInput")]
		public bool EnableManualInput => this.Value<bool>("enableManualInput");

		///<summary>
		/// Event Category: Indicate the category of event. Choose from these 3 categories: Personal Development, Work-Life Balance, Networking
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventCategory")]
		public IEnumerable<string> EventCategory => this.Value<IEnumerable<string>>("eventCategory");

		///<summary>
		/// Event Contents: Add description, details, images about the event. This is displayed on the selected Event page.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventContents")]
		public IHtmlString EventContents => this.Value<IHtmlString>("eventContents");

		///<summary>
		/// Event Date and Time: Type in Date, Time, Timezone, etc.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventDateAndTime")]
		public string EventDateAndTime => this.Value<string>("eventDateAndTime");

		///<summary>
		/// Event Date From
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventDateFrom")]
		public DateTime EventDateFrom => this.Value<DateTime>("eventDateFrom");

		///<summary>
		/// Event Date To
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventDateTo")]
		public DateTime EventDateTo => this.Value<DateTime>("eventDateTo");

		///<summary>
		/// Event Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventName")]
		public string EventName => this.Value<string>("eventName");

		///<summary>
		/// Event Poster
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventPoster")]
		public IPublishedContent EventPoster => this.Value<IPublishedContent>("eventPoster");

		///<summary>
		/// Event Poster Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventPosterAltTag")]
		public string EventPosterAltTag => this.Value<string>("eventPosterAltTag");

		///<summary>
		/// Hosted By Partner?
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("hostedByPartner")]
		public bool HostedByPartner => this.Value<bool>("hostedByPartner");

		///<summary>
		/// KMC Webinar?: If the event type is Webinar, enable this button instead.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("kMCWebinar")]
		public bool KMcwebinar => this.Value<bool>("kMCWebinar");

		///<summary>
		/// Landing Page Link: Hubspot Landing page link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("landingPageLink")]
		public string LandingPageLink => this.Value<string>("landingPageLink");

		///<summary>
		/// Listen on Spotify CTA: CTA Button Label
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("listenOnSpotifyCTA")]
		public string ListenOnSpotifyCta => this.Value<string>("listenOnSpotifyCTA");

		///<summary>
		/// Listen to Spotify Heading: This CTA is for visitors who have already signed up.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("listenToSpotifyHeading")]
		public IHtmlString ListenToSpotifyHeading => this.Value<IHtmlString>("listenToSpotifyHeading");

		///<summary>
		/// Partner Event Registration Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("partnerEventRegistrationLink")]
		public string PartnerEventRegistrationLink => this.Value<string>("partnerEventRegistrationLink");

		///<summary>
		/// Podcast Page?: If the event type is a Podcast, enable this button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("podcastPage")]
		public bool PodcastPage => this.Value<bool>("podcastPage");

		///<summary>
		/// Podcast Sign Up Form: Paste the Hubspot form script
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("podcastSignUpForm")]
		public string PodcastSignUpForm => this.Value<string>("podcastSignUpForm");

		///<summary>
		/// Podcast Sign Up Form Heading: H2 Form Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("podcastSignUpFormHeading")]
		public string PodcastSignUpFormHeading => this.Value<string>("podcastSignUpFormHeading");

		///<summary>
		/// Redirect to Hubspot Landing Page?: Will open a new tab with the landing page link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("redirectToHubspotLandingPage")]
		public bool RedirectToHubspotLandingPage => this.Value<bool>("redirectToHubspotLandingPage");

		///<summary>
		/// Spotify Link: Redirect to Spotify
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("spotifyLink")]
		public string SpotifyLink => this.Value<string>("spotifyLink");

		///<summary>
		/// Watch On Demand?: Show Watch On Demand form.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("watchOnDemand")]
		public bool WatchOnDemand => this.Value<bool>("watchOnDemand");

		///<summary>
		/// Webinar CTA
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("webinarCTA")]
		public string WebinarCta => this.Value<string>("webinarCTA");

		///<summary>
		/// Webinar Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("webinarLink")]
		public string WebinarLink => this.Value<string>("webinarLink");

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEO.GetMetaDescription(this);

		///<summary>
		/// Navigation Item Name: Input name of nav item if it's different from the page name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("navigationItemName")]
		public string NavigationItemName => SEO.GetNavigationItemName(this);

		///<summary>
		/// Og Image: 600 x 600 px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("ogImage")]
		public IPublishedContent OgImage => SEO.GetOgImage(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => SEO.GetPageTitle(this);

		///<summary>
		/// Schema Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("schema")]
		public IEnumerable<IPublishedElement> Schema => SEO.GetSchema(this);

		///<summary>
		/// Structured Data: Add Structured Data from Schema.org
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("structuredData")]
		public string StructuredData => SEO.GetStructuredData(this);

		///<summary>
		/// Hide From Xml SiteMap: Whether to show this page on the XML Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("hideFromXmlSiteMap")]
		public bool HideFromXmlSiteMap => XmlSiteMapSettings.GetHideFromXmlSiteMap(this);

		///<summary>
		/// Search Engine Change Frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public string SearchEngineChangeFrequency => XmlSiteMapSettings.GetSearchEngineChangeFrequency(this);

		///<summary>
		/// Search Engine Relative Priority: Indicate the relevant priority of this page compared relatively to the rest of the site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public decimal SearchEngineRelativePriority => XmlSiteMapSettings.GetSearchEngineRelativePriority(this);
	}
}
