//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "featuredBanner"
	/// <summary>Featured Banner</summary>
	public partial interface IFeaturedBanner : IPublishedContent
	{
		/// <summary>Banner Alt Tag</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string BannerAltTag { get; }

		/// <summary>Banner Image - Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IPublishedContent BannerImageDesktop { get; }

		/// <summary>Banner Image - Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IPublishedContent BannerImageMobile { get; }

		/// <summary>Banner Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string BannerLink { get; }

		/// <summary>Banner on Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		bool ShowBannerOnPage { get; }
	}

	/// <summary>Featured Banner</summary>
	[PublishedModel("featuredBanner")]
	public partial class FeaturedBanner : PublishedContentModel, IFeaturedBanner
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "featuredBanner";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeaturedBanner, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FeaturedBanner(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Banner Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerAltTag")]
		public string BannerAltTag => GetBannerAltTag(this);

		/// <summary>Static getter for Banner Alt Tag</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetBannerAltTag(IFeaturedBanner that) => that.Value<string>("bannerAltTag");

		///<summary>
		/// Banner Image - Desktop
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerImageDesktop")]
		public IPublishedContent BannerImageDesktop => GetBannerImageDesktop(this);

		/// <summary>Static getter for Banner Image - Desktop</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IPublishedContent GetBannerImageDesktop(IFeaturedBanner that) => that.Value<IPublishedContent>("bannerImageDesktop");

		///<summary>
		/// Banner Image - Mobile
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerImageMobile")]
		public IPublishedContent BannerImageMobile => GetBannerImageMobile(this);

		/// <summary>Static getter for Banner Image - Mobile</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IPublishedContent GetBannerImageMobile(IFeaturedBanner that) => that.Value<IPublishedContent>("bannerImageMobile");

		///<summary>
		/// Banner Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("bannerLink")]
		public string BannerLink => GetBannerLink(this);

		/// <summary>Static getter for Banner Link</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetBannerLink(IFeaturedBanner that) => that.Value<string>("bannerLink");

		///<summary>
		/// Banner on Page: If a banner should appear on a page, enable the button.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("showBannerOnPage")]
		public bool ShowBannerOnPage => GetShowBannerOnPage(this);

		/// <summary>Static getter for Banner on Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static bool GetShowBannerOnPage(IFeaturedBanner that) => that.Value<bool>("showBannerOnPage");
	}
}
