//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "featuredItem"
	/// <summary>Featured Item</summary>
	public partial interface IFeaturedItem : IPublishedContent
	{
		/// <summary>Appear on Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IEnumerable<string> AppearOnPage { get; }

		/// <summary>Featured Building City</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string FeaturedBuildingCity { get; }

		/// <summary>Featured Building Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string FeaturedBuildingName { get; }

		/// <summary>Featured Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IHtmlString FeaturedDescription { get; }

		/// <summary>Featured Photo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IPublishedContent FeaturedPhoto { get; }

		/// <summary>Featured Photo Alt Tag</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		string FeaturedPhotoAltTag { get; }
	}

	/// <summary>Featured Item</summary>
	[PublishedModel("featuredItem")]
	public partial class FeaturedItem : PublishedContentModel, IFeaturedItem
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "featuredItem";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeaturedItem, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FeaturedItem(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Appear on Page
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("appearOnPage")]
		public IEnumerable<string> AppearOnPage => GetAppearOnPage(this);

		/// <summary>Static getter for Appear on Page</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IEnumerable<string> GetAppearOnPage(IFeaturedItem that) => that.Value<IEnumerable<string>>("appearOnPage");

		///<summary>
		/// Featured Building City
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredBuildingCity")]
		public string FeaturedBuildingCity => GetFeaturedBuildingCity(this);

		/// <summary>Static getter for Featured Building City</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetFeaturedBuildingCity(IFeaturedItem that) => that.Value<string>("featuredBuildingCity");

		///<summary>
		/// Featured Building Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredBuildingName")]
		public string FeaturedBuildingName => GetFeaturedBuildingName(this);

		/// <summary>Static getter for Featured Building Name</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetFeaturedBuildingName(IFeaturedItem that) => that.Value<string>("featuredBuildingName");

		///<summary>
		/// Featured Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredDescription")]
		public IHtmlString FeaturedDescription => GetFeaturedDescription(this);

		/// <summary>Static getter for Featured Description</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IHtmlString GetFeaturedDescription(IFeaturedItem that) => that.Value<IHtmlString>("featuredDescription");

		///<summary>
		/// Featured Photo: Small featured photo displayed on cards and carousel. Size: 428x175px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredPhoto")]
		public IPublishedContent FeaturedPhoto => GetFeaturedPhoto(this);

		/// <summary>Static getter for Featured Photo</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IPublishedContent GetFeaturedPhoto(IFeaturedItem that) => that.Value<IPublishedContent>("featuredPhoto");

		///<summary>
		/// Featured Photo Alt Tag
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredPhotoAltTag")]
		public string FeaturedPhotoAltTag => GetFeaturedPhotoAltTag(this);

		/// <summary>Static getter for Featured Photo Alt Tag</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static string GetFeaturedPhotoAltTag(IFeaturedItem that) => that.Value<string>("featuredPhotoAltTag");
	}
}
