//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	// Mixin Content Type with alias "featuredLocationsParagraph"
	/// <summary>Featured Locations Contents</summary>
	public partial interface IFeaturedLocationsParagraph : IPublishedContent
	{
		/// <summary>Featured Location Div Bg Texture</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IPublishedContent FeaturedLocationDivBgTexture { get; }

		/// <summary>Featured Location Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IHtmlString FeaturedLocationHeading { get; }

		/// <summary>Featured Location Paragraph</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		IHtmlString FeaturedLocationParagraph { get; }
	}

	/// <summary>Featured Locations Contents</summary>
	[PublishedModel("featuredLocationsParagraph")]
	public partial class FeaturedLocationsParagraph : PublishedContentModel, IFeaturedLocationsParagraph
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "featuredLocationsParagraph";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<FeaturedLocationsParagraph, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public FeaturedLocationsParagraph(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Featured Location Div Bg Texture: Transparent Texture behind the Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredLocationDivBgTexture")]
		public IPublishedContent FeaturedLocationDivBgTexture => GetFeaturedLocationDivBgTexture(this);

		/// <summary>Static getter for Featured Location Div Bg Texture</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IPublishedContent GetFeaturedLocationDivBgTexture(IFeaturedLocationsParagraph that) => that.Value<IPublishedContent>("featuredLocationDivBgTexture");

		///<summary>
		/// Featured Location Heading: Heading Inside Orange Container. It is displayed before the paragraph and 6 cards of featured locations.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredLocationHeading")]
		public IHtmlString FeaturedLocationHeading => GetFeaturedLocationHeading(this);

		/// <summary>Static getter for Featured Location Heading</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IHtmlString GetFeaturedLocationHeading(IFeaturedLocationsParagraph that) => that.Value<IHtmlString>("featuredLocationHeading");

		///<summary>
		/// Featured Location Paragraph
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("featuredLocationParagraph")]
		public IHtmlString FeaturedLocationParagraph => GetFeaturedLocationParagraph(this);

		/// <summary>Static getter for Featured Location Paragraph</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static IHtmlString GetFeaturedLocationParagraph(IFeaturedLocationsParagraph that) => that.Value<IHtmlString>("featuredLocationParagraph");
	}
}
