//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v8.0.4
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedModels
{
	/// <summary>SFI About</summary>
	[PublishedModel("sFIAbout")]
	public partial class SFiabout : PublishedContentModel, IPageBanner, ISEO, IXmlSiteMapSettings
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const string ModelTypeAlias = "sFIAbout";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public new static PublishedContentType GetModelContentType()
			=> PublishedModelUtility.GetModelContentType(ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SFiabout, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(), selector);
#pragma warning restore 0109

		// ctor
		public SFiabout(IPublishedContent content)
			: base(content)
		{ }

		// properties

		///<summary>
		/// Events Anchor Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventsAnchorLink")]
		public string EventsAnchorLink => this.Value<string>("eventsAnchorLink");

		///<summary>
		/// Events Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventsButtonText")]
		public string EventsButtonText => this.Value<string>("eventsButtonText");

		///<summary>
		/// Events  Carousel Images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventsCarouselImages")]
		public IEnumerable<IPublishedContent> EventsCarouselImages => this.Value<IEnumerable<IPublishedContent>>("eventsCarouselImages");

		///<summary>
		/// Events Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventsContent")]
		public IHtmlString EventsContent => this.Value<IHtmlString>("eventsContent");

		///<summary>
		/// Events Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventsDescription")]
		public IHtmlString EventsDescription => this.Value<IHtmlString>("eventsDescription");

		///<summary>
		/// Events Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("eventsHeading")]
		public IHtmlString EventsHeading => this.Value<IHtmlString>("eventsHeading");

		///<summary>
		/// Join the Program Button Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("joinTheProgramButtonLink")]
		public string JoinTheProgramButtonLink => this.Value<string>("joinTheProgramButtonLink");

		///<summary>
		/// Join the Program Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("joinTheProgramButtonText")]
		public string JoinTheProgramButtonText => this.Value<string>("joinTheProgramButtonText");

		///<summary>
		/// Join the Program Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("joinTheProgramContent")]
		public IHtmlString JoinTheProgramContent => this.Value<IHtmlString>("joinTheProgramContent");

		///<summary>
		/// Mentoring Anchor Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("mentoringAnchorLink")]
		public string MentoringAnchorLink => this.Value<string>("mentoringAnchorLink");

		///<summary>
		/// Mentoring Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("mentoringButtonText")]
		public string MentoringButtonText => this.Value<string>("mentoringButtonText");

		///<summary>
		/// Mentoring Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("mentoringContent")]
		public IHtmlString MentoringContent => this.Value<IHtmlString>("mentoringContent");

		///<summary>
		/// Mentoring Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("mentoringHeading")]
		public IHtmlString MentoringHeading => this.Value<IHtmlString>("mentoringHeading");

		///<summary>
		/// Mentors Carousel Images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("mentorsCarouselImages")]
		public IEnumerable<IPublishedContent> MentorsCarouselImages => this.Value<IEnumerable<IPublishedContent>>("mentorsCarouselImages");

		///<summary>
		/// Step 1 Contents
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("step1Contents")]
		public IHtmlString Step1Contents => this.Value<IHtmlString>("step1Contents");

		///<summary>
		/// Step 2 Contents
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("step2Contents")]
		public IHtmlString Step2Contents => this.Value<IHtmlString>("step2Contents");

		///<summary>
		/// Workspace Box 1 Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspaceBox1Content")]
		public IHtmlString WorkspaceBox1Content => this.Value<IHtmlString>("workspaceBox1Content");

		///<summary>
		/// Workspace Box 2 Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspaceBox2Content")]
		public IHtmlString WorkspaceBox2Content => this.Value<IHtmlString>("workspaceBox2Content");

		///<summary>
		/// Workspace Box 3 Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspaceBox3Content")]
		public IHtmlString WorkspaceBox3Content => this.Value<IHtmlString>("workspaceBox3Content");

		///<summary>
		/// Workspaces Anchor Link
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspacesAnchorLink")]
		public string WorkspacesAnchorLink => this.Value<string>("workspacesAnchorLink");

		///<summary>
		/// Workspaces Button Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspacesButtonText")]
		public string WorkspacesButtonText => this.Value<string>("workspacesButtonText");

		///<summary>
		/// Workspaces Carousel Images
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspacesCarouselImages")]
		public IEnumerable<IPublishedContent> WorkspacesCarouselImages => this.Value<IEnumerable<IPublishedContent>>("workspacesCarouselImages");

		///<summary>
		/// Workspaces Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspacesContent")]
		public IHtmlString WorkspacesContent => this.Value<IHtmlString>("workspacesContent");

		///<summary>
		/// Workspaces Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("workspacesHeading")]
		public IHtmlString WorkspacesHeading => this.Value<IHtmlString>("workspacesHeading");

		///<summary>
		/// Full Width Bg Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("fullWidthBgImage")]
		public IPublishedContent FullWidthBgImage => PageBanner.GetFullWidthBgImage(this);

		///<summary>
		/// Heading and Sub Heading
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("headingAndSubHeading")]
		public IHtmlString HeadingAndSubHeading => PageBanner.GetHeadingAndSubHeading(this);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("metaDescription")]
		public string MetaDescription => SEO.GetMetaDescription(this);

		///<summary>
		/// Navigation Item Name: Input name of nav item if it's different from the page name.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("navigationItemName")]
		public string NavigationItemName => SEO.GetNavigationItemName(this);

		///<summary>
		/// Og Image: 600 x 600 px
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("ogImage")]
		public IPublishedContent OgImage => SEO.GetOgImage(this);

		///<summary>
		/// Page Title
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("pageTitle")]
		public string PageTitle => SEO.GetPageTitle(this);

		///<summary>
		/// Schema Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("schema")]
		public IEnumerable<IPublishedElement> Schema => SEO.GetSchema(this);

		///<summary>
		/// Structured Data: Add Structured Data from Schema.org
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("structuredData")]
		public string StructuredData => SEO.GetStructuredData(this);

		///<summary>
		/// Hide From Xml SiteMap: Whether to show this page on the XML Sitemap
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("hideFromXmlSiteMap")]
		public bool HideFromXmlSiteMap => XmlSiteMapSettings.GetHideFromXmlSiteMap(this);

		///<summary>
		/// Search Engine Change Frequency
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineChangeFrequency")]
		public string SearchEngineChangeFrequency => XmlSiteMapSettings.GetSearchEngineChangeFrequency(this);

		///<summary>
		/// Search Engine Relative Priority: Indicate the relevant priority of this page compared relatively to the rest of the site.
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder", "8.0.4")]
		[ImplementPropertyType("searchEngineRelativePriority")]
		public decimal SearchEngineRelativePriority => XmlSiteMapSettings.GetSearchEngineRelativePriority(this);
	}
}
